### ISSUE TITLE
Remove legacy hostnames

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-api-reference#129]
### Description

To improve the developer experience and easen our support and training burden all existing references to  `*.sphere.io` and `.commercetools.co`  host names should be removed in favor of not defaulting to a specific region (a common complaint of US and AWS customers is that EU is defaulted everywhere) or, if needed for backwards compatibility, be replaced with the new `*.europe-west1.gcp.commercetools.com` notation. 

The convention for placeholder-based base URLs is now `https://api.{region}.{cloudProvider}.commercetools.com/`

### Expected Behavior

full text search over the repository for ".sphere.io"  and ".commercetools.co" should yield zero results

### Context

https://docs.commercetools.com/release-notes#releases-2020-02-03-aws-and-new-hostnames

**Comment by nkuehn** [comment]
Thanks and congratulations to the speed @jenschude :-) 

A follow-up question:  To move on to using the RAML for documentation we would need to introduce actual [base URI parameters
](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#base-uri-and-base-uri-parameters) with enumerations of the available regions and cloud Providers. 

Is there something in the current user base that speaks against that?  Maybe setting a default value in the uriParameters could retain backwards compatibility?

**Comment by jenschude** [comment]
That's a good question how to deal with them.

Especially as they can't be freely combined you would have to create a list with the complete list. But the parameter is a little bit misleading as it consists of two values. Maybe OAS3 is here more correct in allowing multiple server hosts.

```
baseUri: https://api.{regionProvider}.commercetools.com/
baseUriParameters:
  regionProvider:
    type: string
    default: "europe-west1.gcp"
    enum:
      - "us-central1.gcp"
      - "europe-west1.gcp"
      - "us-east-2.aws"
      - "eu-central-1.aws"
```
