### ISSUE TITLE
ResourceIdentifier replaced the Reference in the CartDiscount

### ISSUE THREAD

**Issue by barbara79** [commercetools/commercetools-api-reference#197]
https://github.com/commercetools/commercetools-docs/pull/732

This ticket could create some errors like in sdk tests

**Comment by stmeissner** [comment]
The issue title sounds a bit misleading to me, thus I'll be more explicit:

In [CartDiscountValueGiftLineItemDraft.raml](https://github.com/commercetools/commercetools-api-reference/blob/master/types/cart-discount/CartDiscountValueGiftLineItemDraft.raml) the References should be replaced with ReferenceIdentifiers:
currently:
```
  product:
    type: ProductReference
  variantId:
    type: number
    format: int64
  supplyChannel?:
    type: ChannelReference
  distributionChannel?:
    type: ChannelReference
```
desired:
```
  product:
    type: ProductResourceIdentifier
  variantId:
    type: number
    format: int64
  supplyChannel?:
    type: ChannelResourceIdentifier
  distributionChannel?:
    type: ChannelResourceIdentifier
```
