### ISSUE TITLE
Add API Extension Error responses

### ISSUE THREAD

**Issue by davidweterings** [commercetools/commercetools-api-reference#65]
Could you add the error response for https://docs.commercetools.com/http-api-errors.html#extension-error-responses ?

F.e. `types/error/ExtensionNoResponseError.raml`:

```
#%RAML 1.0 DataType
(package): Error


type: ErrorObject
displayName: ExtensionNoResponseError
discriminatorValue: ExtensionNoResponse
properties:
    extensionId:
        type: string
    extensionKey:
        type: string
```
