### ISSUE TITLE
ApiClient resource inconsistent 'type' under '/{ID}'

### ISSUE THREAD

**Issue by davidweterings** [commercetools/commercetools-api-reference#98]
Context:

We're generating our Go SDK from the RAML definition and noticed a few inconsistencies.
As discussed with Matthias, I'm making a separate issue for each finding.

Issue:
`resources/api-clients.raml` key `/{ID}` has `type: base`, while most other resources define something like this:

```
    type:
      baseResource:
        uriParameterName: ID
        resourceType: Channel
        resourceUpdateType: Update
        resourceUpdateExample: !include ../examples/channel-update.example.json
        resourceExample: !include ../examples/channel.example.json
```
